version: "3.7"

services:
  server:
    image: gitea/gitea:latest
    environment:
      # Application name, used in the page title
      - APP_NAME="CHANGE THIS"
      # Run mode, dev/prod
      - RUN_MODE=prod
      # Only admin can create accounts
      - DISABLE_REGISTRATION=true
      # Require signin to view anything
      - REQUIRE_SIGNIN_VIEW=true
      # Database parameters
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD="REPLACED_AT_RUNTIME"
    command: sh -c "export DB_PASSWD=$$(cat /run/secrets/gitea_db_passwd) && /bin/s6-svscan /etc/s6"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - db
    secrets:
      - gitea_db_passwd
    volumes:
      - data:/data
    ports:
      - "3000:3000"
      - "2201:22"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_passwd
      - POSTGRES_DB=gitea
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - db
    secrets:
      - gitea_db_passwd
    volumes:
      - db:/var/lib/postgresql/data

networks:
  db:
    driver: overlay

secrets:
  gitea_db_passwd:
    external: true

volumes:
  data:
    driver: local
  db:
    driver: local
