version: "3.7"

services:
  server:
    image: gitea/gitea:1.7.3
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=RbJpoLpkPHZQE8g93Alb
    command: /bin/s6-svscan /etc/s6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - db
    secrets:
      - gitea_db_passwd
    volumes:
      - data:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitea_db_passwd
      - POSTGRES_DB=gitea
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - db
    secrets:
      - gitea_db_passwd
    volumes:
      - db:/var/lib/postgresql/data

networks:
  db:
    driver: overlay

secrets:
  gitea_db_passwd:
    external: true

volumes:
  data:
    driver: local
  db:
    driver: local
